version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
     - "80:80"
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/default.conf
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app:consistent
      - node_modules:/usr/src/app/node_modules:consistent
volumes:
  npm_cache:
  node_modules: